name: Playwright Screenshot

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install chromium --with-deps

      - name: Run script
        run: |
          python main.py

      - name: Upload screenshot
        uses: actions/upload-artifact@v7
        with:
          name: output
          path: output/
